[package]
name = "minesweeper-pison-rs"
version = "0.1.0"
authors = ["Galen Elias <gelias@gmail.com>"]

[dependencies]
piston_window = "*"
rand = "*"
piston2d-opengl_graphics = "*"
piston2d-graphics = "*"
itertools = "*"